version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
    - echo installing maven...
    - apt-get update -y
    - apt-get install -y maven
  build:
    commands:
    - echo building FarmStay
    - java -version
    - mvn install
post_build:
    commands:
    - echo Build completed on `date`
    - mvn package
    - mv target/FarmWorkSpringBoot-0.0.1-SNAPSHOT.war FarmWorkSpringBoot-0.0.1-SNAPSHOT.war
artifacts:
  files:
  - FarmWorkSpringBoot-0.0.1-SNAPSHOT.war
  - .ebextensions/**/*