version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
    - echo installing maven...
    - apt-get update -y
    - apt-get install -y maven
  build:
    commands:
    - echo building FarmStay
    - java -version
    - mvn install
artifacts:
  files:
    - '**/*'
  base-directory: 'target/FarmWorkSpringBoot-0.0.1-SNAPSHOT.war'
cache:
  paths:
  - '/root/.m2/**/*'