version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
    - echo installing maven...
    - apt-get update -y
    - apt-get install -y maven
  build:
    commands:
    - echo building FarmStay
    - java -version
    - mvn install
artifacts:
  files:
    - '**/*'
    - echo $CODEBUILD_SRC_DIR
  base-directory: '/target/farm-stay'
cache:
  paths:
  - '/root/.m2/**/*'